<footer id="footer" class="wrapper">
  <div class="inner">
  <!--   <div id="footer-copyright">
    &copy; {{ moment(Date.now()).year() }} <a href="https://www.wilddog.com/" target="_blank">野狗</a><br>
  </div> -->
    <div id="footer-links">
		<a href="/overview/index.html" class="footer-link">文档</a>
		<a href="https://www.wilddog.com/download" class="footer-link">SDK下载</a>
		<a href="https://www.wilddog.com/product/pricing" class="footer-link">价格</a>
		<a href="https://life.wilddog.com/wilddog-contact.html" class="footer-link">联系我们</a>
		<a href="https://wilddog.kf5.com/user/login/?_ga=1.257821899.1360428381.1464868258" class="footer-link">客服工单</a>
    </div>
  </div>
</footer>
